name: listwhatever
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  another_xlider: ^3.0.2
  autocomplete_textfield: ^2.0.1
  bloc: ^8.1.4
  cloud_firestore: ^5.5.1
  device_info_plus: ^11.2.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_ui_firestore: ^1.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_form_builder: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_typeahead: ^5.2.0
  form_builder_extra_fields: ^11.0.0
  form_builder_image_picker: ^4.1.0
  form_builder_validators: ^11.0.0
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  hugeicons: ^0.0.7
  image_picker: ^1.0.7
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.0.2+1
  meta: ^1.15.0
  sign_in_with_apple: ^6.1.4

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
