// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDurmbiDLe8JSc1tPrXyaIiV-eG8A9BnpQ',
    appId: '1:271831505512:web:24cbeeb3a02ed9461679dd',
    messagingSenderId: '271831505512',
    projectId: 'listanything-2b9b0',
    authDomain: 'listanything-2b9b0.firebaseapp.com',
    storageBucket: 'listanything-2b9b0.appspot.com',
    measurementId: 'G-X8LW5CVVLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYImfpCD-Q1Im7MfqTBC74BFTi_eR1v7w',
    appId: '1:271831505512:android:c6093485d36f1aba1679dd',
    messagingSenderId: '271831505512',
    projectId: 'listanything-2b9b0',
    storageBucket: 'listanything-2b9b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhpJQvqb03YWARDS7EwPpItNiuqpk1J_A',
    appId: '1:271831505512:ios:660244af695128921679dd',
    messagingSenderId: '271831505512',
    projectId: 'listanything-2b9b0',
    storageBucket: 'listanything-2b9b0.appspot.com',
    androidClientId: '271831505512-1m3r8velqj41jl7rehdhblkeok1a457b.apps.googleusercontent.com',
    iosClientId: '271831505512-vcvpj40vo44irajhgnk47u5uuupi30ip.apps.googleusercontent.com',
    iosBundleId: 'com.anywhostudios.listanything',
  );
}
