// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      TargetPlatform.iOS => ios,
      TargetPlatform.macOS => macos,
      TargetPlatform.windows => throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        ),
      TargetPlatform.linux => throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        ),
      TargetPlatform.fuchsia => throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        ),
    };
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKx28ZXQZGgqDDKPjfgzz84am46oBBTik',
    appId: '1:988968351840:web:9be3573dcb899a4d8fab05',
    messagingSenderId: '988968351840',
    projectId: 'golfgames-ffddc',
    authDomain: 'golfgames-ffddc.firebaseapp.com',
    storageBucket: 'golfgames-ffddc.appspot.com',
    measurementId: 'G-824KTBFHWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBew7swRKfhvbCAOY1bSbWnDtGi26gXqTA',
    appId: '1:988968351840:android:6deef9d1a656a4148fab05',
    messagingSenderId: '988968351840',
    projectId: 'golfgames-ffddc',
    storageBucket: 'golfgames-ffddc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCcoHmJaT8CWwiFcaTgalZaDy8g4xEbxc',
    appId: '1:988968351840:ios:d450dd7a627aa9a38fab05',
    messagingSenderId: '988968351840',
    projectId: 'golfgames-ffddc',
    storageBucket: 'golfgames-ffddc.appspot.com',
    androidClientId:
        '988968351840-0m192jbha4u79kd03l0s2e8lo3204aht.apps.googleusercontent.com',
    iosClientId:
        '988968351840-njfpcbp8jklkp3lql3o9cf0briscqs5n.apps.googleusercontent.com',
    iosBundleId: 'com.anywhostudios.golfgames',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCcoHmJaT8CWwiFcaTgalZaDy8g4xEbxc',
    appId: '1:988968351840:ios:d450dd7a627aa9a38fab05',
    messagingSenderId: '988968351840',
    projectId: 'golfgames-ffddc',
    storageBucket: 'golfgames-ffddc.appspot.com',
    androidClientId:
        '988968351840-0m192jbha4u79kd03l0s2e8lo3204aht.apps.googleusercontent.com',
    iosClientId:
        '988968351840-njfpcbp8jklkp3lql3o9cf0briscqs5n.apps.googleusercontent.com',
    iosBundleId: 'com.anywhostudios.golfgames',
  );
}
